### PR TITLE
src/lib.rs: add distance calculation

### PR DESCRIPTION
**Pull request by gwbres**
Hello @gberrante ,

I introduced the distance calculation between two decimal degrees coordinates.   
Result is in [m].   
I provide a test method and verified on my side.

Signed-off-by: Guillaume W. Bres <guillaume.bressaix@gmail.com>

### CODE REVIEW

**Comment by gberrante** [comment]
Thanks for your contribution. I will review the code and let you know.
Happy holidays in the meanwhile

**Comment by gwbres** [comment]
> Thanks for your contribution. I will review the code and let you know. Happy holidays in the meanwhile

Hello, happy holidays to you too :)

**Comment by clintfred** [comment]
Hi! Can this be merged and released?

**Comment by gwbres** [comment]
Hello guys, 

@gberrante could you provide an official tag? 
This way I can have my other libs rely officially on `map_3d` instead of custom local code for similar features

**Pull request merged**
